### ISSUE TITLE
Exceptions in LoaderBase and PostValidation

### ISSUE THREAD

**Issue by CsabaHalmagyi** [PDXFinder/pdxfinder#271]
- [ ] Markers exception gone
- [x] Validation exception gone

There are some exceptions occurring after the software upgrade:

04:44:16::280 [1;31mERROR[0;39m  org.pdxfinder.dataloaders.LoaderBase     : Exception occurred in loaderbase

java.lang.NullPointerException: null
	at org.pdxfinder.dataloaders.LoadJAXData.step11LoadBreastMarkers(LoadJAXData.java:161)
	at org.pdxfinder.dataloaders.LoaderBase.globalLoadingOrder(LoaderBase.java:230)
	at org.pdxfinder.dataloaders.LoadJAXData.run(LoadJAXData.java:48)
	at org.pdxfinder.commandline.FinderLoader.callRelevantLoader(FinderLoader.java:189)

And

04:56:58::175 [34mINFO [0;39m  org.pdxfinder.postload.ValidateDB        : ******************************************************
04:56:58::175 [34mINFO [0;39m  org.pdxfinder.postload.ValidateDB        : * Starting validation checks                         *
04:56:58::175 [34mINFO [0;39m  org.pdxfinder.postload.ValidateDB        : ******************************************************
04:56:58::175 [34mINFO [0;39m  org.pdxfinder.postload.ValidateDB        : Looking for sad nodes (nodes without a relationship)
04:56:58::175 [34mINFO [0;39m  org.pdxfinder.postload.ValidateDB        : Looking for patients with multiple treatment summaries
04:56:58::201 [34mINFO [0;39m  org.pdxfinder.postload.ValidateDB        : Validating platforms
04:56:58::228 [31mWARN [0;39m  org.neo4j.ogm.session.Neo4jSession       : Error executing query : 0. Rolling back transaction.
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.neo4j.ogm.context.EntityRowModelMapper.extractColumnValue(EntityRowModelMapper.java:75)
	at org.neo4j.ogm.context.EntityRowModelMapper.map(EntityRowModelMapper.java:64)
	at org.neo4j.ogm.session.delegates.ExecuteQueriesDelegate.lambda$executeAndMap$1(ExecuteQueriesDelegate.java:133)
	at org.neo4j.ogm.session.Neo4jSession.doInTransaction(Neo4jSession.java:579)
	at org.neo4j.ogm.session.Neo4jSession.doInTransaction(Neo4jSession.java:558)
	at org.neo4j.ogm.session.delegates.ExecuteQueriesDelegate.executeAndMap(ExecuteQueriesDelegate.java:124)
	at org.neo4j.ogm.session.delegates.ExecuteQueriesDelegate.query(ExecuteQueriesDelegate.java:94)
	at org.neo4j.ogm.session.Neo4jSession.query(Neo4jSession.java:413)

**Comment by CsabaHalmagyi** [comment]
Old validation methods have been removed.

**Comment by zperova** [comment]
this has to wait until Spring Upgrade is merged back to dev

**Comment by CsabaHalmagyi** [comment]
With the upgrade these exceptions were fixed.

**Comment by zperova** [comment]
done
