### ISSUE TITLE
Investigate H2 upgrade issues

### ISSUE THREAD

**Issue by CsabaHalmagyi** [PDXFinder/pdxfinder#310]
Description:

When running the indexer jenkins encounters the following issue:

14:34:58::993 ERROR  com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Exception during pool initialization.

org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.IllegalStateException: Unable to read the page at position 8521215181699 [1.4.200/6]" [50000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.engine.Database.openDatabase(Database.java:333)
	at org.h2.engine.Database.<init>(Database.java:301)
	at org.h2.engine.Engine.openSession(Engine.java:74)
	at org.h2.engine.Engine.openSession(Engine.java:192)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
	at org.h2.engine.Engine.createSession(Engine.java:166)
	at org.h2.engine.Engine.createSession(Engine.java:29)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)

Acceptance criteria:
- [x] H2 driver works properly
- [x] Jenkins deploys the app

**Comment by CsabaHalmagyi** [comment]
This is due to a bug that has been introduced in version 1.4.200. We would need to do manual upgrades of the database, therefore I downgraded the database version to 1.4.197 This is the stable version we can use with the current Spring Boot version.

**Comment by zperova** [comment]
thanks, @CsabaHalmagyi well done digging to the bottom of it!
